export const scrutin = [
  {
    id: 1,
    number: 1920,
    based: "contre",
    connard: "pour",
  },
  {
    id: 2,
    number: 2077,
    based: "contre",
    connard: "pour",
  },
  {
    id: 3,
    number: 3725,
    based: "contre",
    connard: "pour",
  },
  {
    id: 4,
    number: 3261,
    based: "pour",
    connard: "contre",
  },
  {
    id: 5,
    number: 3653,
    based: "pour",
    connard: "contre",
  },
  {
    id: 6,
    number: 3643,
    based: "pour",
    connard: "contre",
  },
  {
    id: 7,
    number: 663,
    based: "contre",
    connard: "pour",
  },
  {
    id: 8,
    number: 1361,
    based: "contre",
    connard: "pour",
  },
  {
    id: 9,
    number: 3030,
    based: "contre",
    connard: "pour",
  },
  {
    id: 10,
    number: 2717,
    based: "contre",
    connard: "pour",
  },
  {
    id: 11,
    number: 1843,
    based: "pour",
    connard: "contre",
  },
  {
    id: 12,
    number: 2988,
    based: "contre",
    connard: "pour",
  },
  {
    id: 13,
    number: 3332,
    based: "pour",
    connard: "contre",
  },
  {
    id: 13,
    number: 1462,
    based: "pour",
    connard: "contre",
  },
  {
    id: 14,
    number: 3101,
    based: "pour",
    connard: "contre",
  },
  {
    id: 15,
    number: 3289,
    based: "pour",
    connard: "contre",
  },
  {
    id: 16,
    number: 1402,
    based: "pour",
    connard: "contre",
  },
  {
    id: 17,
    number: 793,
    based: "pour",
    connard: "contre",
  },
  {
    id: 18,
    number: 931,
    based: "pour",
    connard: "contre",
  },
  {
    id: 19,
    number: 3382,
    based: "pour",
    connard: "contre",
  },
  {
    id: 20,
    number: 3656,
    based: "pour",
    connard: "contre",
  },
  {
    id: 21,
    number: 838,
    based: "pour",
    connard: "contre",
  },
];
